### ISSUE TITLE
Replace`realpath` in bash script for MacOS compatibility

### ISSUE THREAD

**Issue by Dekker1** [informarte/yuck#10]
While installing Yuck I discovered that the Bash script `yuck` I discover that it uses `realpath` to find the absolute path of the location of the script. Although this in itself is not a problem, (at least the latest version of) MacOS does not contain this tool by default.

It can be installed using Homebrew (`brew install coreutils`), but since Bash can do this by itself it feels like a dependency that could be easily be removed.

In previous scripts I've used
```
DIR="$( cd "$( dirname "$0" )" && pwd )"
```
which seems to work well.

**Comment by informarte** [comment]
Thanks for the report!
I will address this issue in the upcoming release.

**Comment by informarte** [comment]
The issue with the proposed solution is that it does not handle the symbolic link `/usr/bin/yuck -> /usr/share/yuck/bin/yuck` used in the Debian package. So I decided to document the dependency on `coreutils`.

**Comment by Dekker1** [comment]
Although I'm also happy if it gets documented. Maybe it is still worthwhile considering this SO answer that (at least promises to) work with symbolic links: https://stackoverflow.com/a/3572105/1351597

**Comment by informarte** [comment]
I looked through all the proposals on SO and found that each of them has issues regarding functionality or Linux compatibility. As I do not want to make assumptions on how users set up their system (maybe someone has symbolic links on their `PATH`), I decided that it is better to stick with `realpath` from `coreutils`.
