### ISSUE TITLE
MiniZinc: type error: FlatZinc builtins are not allowed to have arguments of type array[$_] of var opt top

### ISSUE THREAD

**Issue by FrancoisAlexandreTremblay** [informarte/yuck#16]
I'm trying to run this simple code given in the README.md:

```
include "disjunctive.mzn";
include "yuck.mzn";

array [1..4] of var int: o;
array [1..4] of var int: d;

constraint o[1] in 2..5 /\ d[1] in 2..4;
constraint o[2] in 2..4 /\ d[2] in 1..6;
constraint o[3] in 3..6 /\ d[3] in 4..4;
constraint o[4] in 2..7 /\ d[4] in 1..3;

var int: overlap = bool2costs(disjunctive(o, d));

solve minimize(overlap);

output ["o = ", show(o), "\n", "d = ", show(d), "\n", "overlap = ", show(overlap)];
```

I get the following error : 

```
redefinitions:2.25-50: 
MiniZinc: type error: FlatZinc builtins are not allowed to have arguments of type array[$_] of var opt top
redefinitions:2.25-50: 
MiniZinc: type error: FlatZinc builtins are not allowed to have arguments of type array[$_] of var opt top
redefinitions:2.25-50: 
MiniZinc: type error: FlatZinc builtins are not allowed to have arguments of type array[$_] of var opt top
redefinitions:2.25-50: 
MiniZinc: type error: FlatZinc builtins are not allowed to have arguments of type array[$_] of var opt top 
Process finished with non-zero exit code 1. 
Finished in 135msec.
```
I'm on MacOS Montery (version 12.6.6). I have Java runtime available and installed `coreutils` package with the Homebrew command. I have Minizinc IDE version `2.8.1`. I also tried to downgrade the Minizinc version (to `2.6.2`) but I still get the same error.

**Comment by informarte** [comment]
MiniZinc 2.8.1 introduced breaking changes which made it incompatible with a couple of solvers, including Yuck. The next Yuck release will fix this issue but it will have to wait until the MiniZinc developers have fixed all the bugs which are currently in the way of replacing MiniZinc 2.7.6 with 2.8.x in my test environment. For the time being, please use [Yuck release 20230623](https://github.com/informarte/yuck/releases/tag/20230623) together with MiniZinc 2.7.6. If you want to use MiniZinc 2.6.4, then please use it together with [Yuck release 20221101](https://github.com/informarte/yuck/releases/tag/20221101).
