### ISSUE TITLE
Put a reference to yuck in the readme!

### ISSUE THREAD

**Issue by ChrisJefferson** [informarte/yuck#3]
Hi,

I wanted to cite yuck. I wasn't sure what was the best reference.

**Comment by informarte** [comment]
There are no publications on Yuck, so `https://github.com/informarte/yuck` is currently the best reference.

**Comment by ChrisJefferson** [comment]
Thanks. I have been using yuck and found it both high performance, and easy to use.

**Comment by informarte** [comment]
Cool, what kind of problem are you solving?

**Comment by ChrisJefferson** [comment]
We were using it as part of a set of solvers to test a new algorithm. I'll post back when the paper is publicly published somewhere. It did very well :)
