### ISSUE TITLE
Error when trying to solve cvrptw problems

### ISSUE THREAD

**Issue by marcosrobertosilva** [informarte/yuck#9]
Hi.
I'm trying to solve CVRPTW model available in https://github.com/informarte/minizinc-benchmarks/tree/yuck-testing
but I'm getting the following error message:

![image](https://user-images.githubusercontent.com/1138647/129736368-0c74dd99-a600-4259-a498-50fb4e088ba7.png)

Do you know the cause of this error?

I can confirm that yuck is installed correctly and I'm able to solve other problems, such as vrplc
![image](https://user-images.githubusercontent.com/1138647/129736079-a5411e76-06dd-427a-bcf0-972904c3d5b6.png)

Thank you

Marcos

**Comment by informarte** [comment]
`MaxKToMinKRatio` is a parameter described in the paper [Extending Yuck for Vehicle Routing](https://github.com/informarte/yuck/releases/download/20210501/Extending_Yuck_for_Vehicle_Routing.pdf), page 5. It affects performance and is therefore not part of the instance data. You can define it on the command line like this:
```
minizinc --solver yuck -DMaxKToMinKRatio=4 cvrptw_yuck.mzn Solomon/C101.100.10.dzn
```

**Comment by marcosrobertosilva** [comment]
Thank you very much and congratulations for the great job on **yuck**.
